# Configurações do Banco de Dados

# Configura??es do Banco de Dados
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=8rdWb7sklHUuMnZYydRf2j2vo5UIoywT
spring.datasource.url=jdbc:postgresql://dpg-cv9chfd2ng1s73d3668g-a

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Configurações do Servidor de Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jucaodamontanha@gmail.com
spring.mail.password=dptk rpqc fsjd vokr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true