spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.enable_lazy_loading=true
spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto=drop-and-create
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query.cache=false
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory
spring.jpa.properties.javax.cache.provider=org.ehcache.jsr107.EhcacheCachingProvider
spring.jpa.properties.javax.cache.uri=classpath:ehcache.xml

SENDGRID_API_KEY=${SENDGRID_API_KEY}
SENDGRID_FROM_EMAIL=${SENDGRID_FROM_EMAIL}


logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always 
management.endpoint.health.probes.enabled=true
management.health.db.enabled=true
management.health.diskspace.enabled=true


management.health.livenessState.enabled=true
management.health.readinessState.enabled=true

management.metrics.export.prometheus.enabled=true

management.metrics.enable.process.files.enabled=true
management.metrics.enable.process.files.opened.enabled=true
management.metrics.enable.process.cpu.enabled=true
management.metrics.enable.process.memory.enabled=true
management.metrics.enable.jvm.buffer.enabled=true
management.metrics.enable.jvm.classes.enabled=true
management.metrics.enable.jvm.gc.enabled=true
management.metrics.enable.jvm.memory.enabled=true
management.metrics.enable.jvm.threads.enabled=true
management.metrics.enable.logback.enabled=true
management.metrics.enable.system.cpu.enabled=true
management.metrics.enable.system.files.enabled=true
management.metrics.enable.system.memory.enabled=true
management.metrics.enable.system.uptime.enabled=true   
management.metrics.enable.http.server.requests.enabled=true
management.metrics.enable.process.uptime.enabled=true
management.metrics.enable.disk.space.enabled=true


management.metrics.enable.redis.enabled=true    
management.metrics.enable.cache.enabled=true